Fix #621 Pulsing light  can't be seen throuhg walls anymore
MrBSmith/XionLeak pull request #640
Opened 2021-06-11 13:08 UTC by MrBSmith

2021-06-11 15:46 UTC, Weact commented
@MrBSmith conflicts

2021-06-11 15:48 UTC, Weact requested changes
conflicts

2021-06-17 08:24 UTC, MrBSmith commented
Conflicts has been fixed

2021-06-17 08:50 UTC, Weact approved these changes

2021-06-17 08:50 UTC, merged