Feature/chain
MrBSmith/XionLeak pull request #745
Opened 2021-08-20 17:57 UTC by Weact

Close #695

2021-08-20 18:06 UTC, Weact commented on Scenes/Actor/ActorBase.gd
> +			set_global_position(grab_node.grabposition_node.get_global_position())
Is there another way to do this ? Only found that to make the character stick

2021-08-20 18:12 UTC, Weact commented on Scenes/ProductionChain/Shader/Script/ProductionChain.shader
> +}
this has been fixed in a future commit

2021-08-20 18:18 UTC, Weact commented on Scenes/ProductionChain/Scripts/ProductionChain.gd
> +	$Path2D/PathFollow2D.set_offset($Path2D/PathFollow2D.get_offset() + speed * delta)
Maybe this needs to be replaced by a node variable ?
this method moves the unit along the path

2021-08-20 19:30 UTC, Weact commented on Scenes/ProductionChain/Scripts/ProductionChain.gd
> +	$Path2D/PathFollow2D.set_offset($Path2D/PathFollow2D.get_offset() + speed * delta)
fixed

2021-08-21 12:55 UTC, MrBSmith requested changes
This is very good, and I'm pretty happy cause I can dig in pretty precise stuff to review, cause the overall code quality is high :)

Here is some minor feedbacks I can make:

- [x] avoid `self` keyword when it's not needed because the engine looks for the node at global scope when refering to it with `self` witch causes performance to drop. In GDscript unlike in othe languages its a thing to avoid when you can

- [ ] code style wise try to add an _ before your functions that you don't want to be accessed from the outside: this is the equivalent for private keyword in many languages. In particular for signal receiving methods

2021-08-21 13:05 UTC, MrBSmith commented on Scenes/ProductionChain/Grab/Grab.gd
> +const GRABBABLE_BODIES : Array = ["ActorBase","BreakableObjectBase"]
You should make that a export var instead of a const IMO so we can modify in in the editor instead of modifiyng it in the code; and maybe doing some per instance changes if needed

2021-08-21 13:08 UTC, MrBSmith commented on Scenes/Actor/ActorBase.gd
> +			set_global_position(grab_node.grabposition_node.get_global_position())
The movement itself could be applied from the hook instead of from the Actor, that way you don't have to have dupliate code for moving other elements that could be grabbed.

2021-08-21 13:14 UTC, MrBSmith requested changes
Hey the overall code quality is pretty high, so that's very good. So I'll put here some general advices and code style feedbacks, and see in the code for more precises feedbacks

- [ ] I can see an issue with the way you implemented the is_grabbed in the actor: the fact that this behaviour is to be shared with other types of gameplay elements (Blocks, Xion Crate, maybe platfroms etc) makes me think you should use composition over inhearitence in that case. If you did a node named Grabbable or Hookable that encapsulate the whole logic of beeing hooked; you could have a single place where the code reside and then just instanciate it in the scenes you want to be grabbable.
That way you wouldn't even have to have a GRABBABLE_BODIES in your hook. You just check if the body as a Grabbable node as a child, and anything could be grabbable no matter its type.

- [ ] avoid `self` keyword when it's not needed because the engine looks for the node at global scope when refering to it with `self` witch causes performance to drop. In GDscript unlike in othe languages its a thing to avoid when you can

- [ ] Try to add a _ befor the name of a function when you don't want it to be accessable from the outside; this is the GDscript equivalent for the private keyword in many languages

2021-08-21 13:15 UTC, MrBSmith commented on Scenes/ProductionChain/Grab/Grab.gd
> +const GRABBABLE_BODIES : Array = ["ActorBase","BreakableObjectBase"]
See the general comment before working on this; as it may be solved otherwise

2021-08-21 13:17 UTC, MrBSmith commented on Scenes/ProductionChain/Shader/Script/ProductionChain.shader
> +}
You mean just do COLOR = new_color; ^^ ?

2021-08-21 16:29 UTC, Weact commented
I think I solved the _ issue, this was only for the on_speed_changed method in productionchain ?

2021-08-22 10:32 UTC, MrBSmith commented on Scenes/Actor/Players/PlayerBase/Scripts/PlayerBase.gd
> +			if is_instance_valid(get_node("Hookable")) and get_node("Hookable").is_hooked():
Maybe you could make an `onready var hookable = $Hookable` in the player to avoid getting it each time, as the player HAS TO have a hookable node anyway

2021-08-22 10:39 UTC, MrBSmith commented on Scenes/InteractiveObjects/BreakableObjects/Blocks/BlockBase.gd
> +	$Hookable.unhook()
This should be done in the hookable node I think, to avoid coding this behaviour everywhere its needed.

You just connect the signal destroyed from its parent (Don't forget to check if it has the signal) and when the signal is received, the hookable unhook itself.

2021-08-22 10:40 UTC, MrBSmith commented on Scenes/ProductionChain/Hook/Hook.gd
> +class_name Grab
The class name doesn't match the file name. Either rename the class Hook or the file Grab

2021-08-22 10:45 UTC, MrBSmith requested changes
Just three general feedbacks:

- [ ] The shader movement looks rather quick compared to the movement of the hooks. Did you try to make it exactly the same speed as the movement by making it equal to `speed * get_physics_process_delta_time()`?

- [ ] Don't forget to remove the bodies from the production chain scene when you're done with the feature

- [ ] Maybe we should make the pinjoint and the hook be a part of a single scene so its easier to instanciate when we are level designing

2021-08-22 11:42 UTC, Weact commented on Scenes/InteractiveObjects/BreakableObjects/Blocks/BlockBase.gd
> +	$Hookable.unhook()
done

2021-08-22 11:42 UTC, Weact commented on Scenes/ProductionChain/Hook/Hook.gd
> +class_name Grab
done

2021-08-22 11:44 UTC, Weact commented on Scenes/Actor/Players/PlayerBase/Scripts/PlayerBase.gd
> +			if is_instance_valid(get_node("Hookable")) and get_node("Hookable").is_hooked():
done

2021-08-22 15:50 UTC, MrBSmith commented on Scenes/ProductionChain/HookFullPart/Hook/Hook.gd
> +	if !is_instance_valid(body) or is_instance_valid(body) and !body.has_node("Hookable"):
A little flaw here; I guess you meant `!is_instance_valid(body) or ( is_instance_valid(body) and !body.has_node("Hookable"))`
It won't result in the same behaviour without the parenthesis

2021-08-22 18:42 UTC, Weact commented on Scenes/ProductionChain/HookFullPart/Hook/Hook.gd
> +	if !is_instance_valid(body) or is_instance_valid(body) and !body.has_node("Hookable"):
done

2021-08-23 10:14 UTC, MrBSmith commented on Scenes/ProductionChain/HookableNode/Hookable.gd
> +var hook_node : WeakRef = null
Maybe just rename this hook_weak_ref so there is no confusion wether the variable contains the reference to the hook or the weak_ref pointing to the hook

2021-08-23 10:19 UTC, MrBSmith commented on Scenes/ProductionChain/HookableNode/Hookable.gd
> +var hook_node : WeakRef = null
Be careful to rename it also when you are accessing it from the outside

2021-08-23 10:22 UTC, MrBSmith commented on Scenes/ProductionChain/HookFullPart/HookFullPart.gd
> +signal freed(hookfullpart)
This signal just redirect the `tree_exiting` one. You might as well use direclty `tree_exiting`

2021-08-23 10:25 UTC, MrBSmith commented on Scenes/ProductionChain/HookableNode/Hookable.gd
> +func get_hook() -> WeakRef:
There is an issue with this function: it's suppossed to return the weakref but it returns what the weakref is pointing at.
That is why it's important to rename the variable.

When you're done renaming it, you might want to do a `get_hook_weakref` that returns the weakref and a `get_hook` that returns the Hook the weakref is pointing at

2021-08-25 09:59 UTC, MrBSmith approved these changes

2021-08-25 10:01 UTC, merged